uploads = []
generated = []

[[outputs]]
id = "vLoU6wTN6r8dsIYyFn_N9"
uri = "file://artifacts/clark-kent/public/tech1.png"
type = "image"
title = "Retrato techno 1 — Máscara cromada"

[[outputs]]
id = "BFo-97Q2YtjDK23LlOXEI"
uri = "file://artifacts/clark-kent/public/tech2.png"
type = "image"
title = "Retrato techno 2 — Visera holográfica"

[[outputs]]
id = "liaiABlAeojHw5C-_R40C"
uri = "file://artifacts/clark-kent/public/tech3.png"
type = "image"
title = "Retrato techno 3 — Gafas espejo futuristas"

[[outputs]]
id = "ZchP9hmvGlcP1cWZN-1c8"
uri = "file://artifacts/clark-kent/public/tech1_2.png"
type = "image"
title = "Avatar 1 — Android teal con circuitos dorados"

[[outputs]]
id = "iOXF_bVlRhmYHiLre0U0k"
uri = "file://artifacts/clark-kent/public/tech2_2.png"
type = "image"
title = "Avatar 2 — Escultura cromada de espejo"

[[outputs]]
id = "TO2yWWlnThMA2iJ7lT45a"
uri = "file://artifacts/clark-kent/public/tech3_2.png"
type = "image"
title = "Avatar 3 — Figura de cristal con datos neon"

[[outputs]]
id = "v2m2-9HA_Yymy93zMYEBM"
uri = "file://artifacts/clark-kent/public/surreal1.png"
type = "image"
title = "Surreal 1 — Mujer porcelana con grulla"

[[outputs]]
id = "7fotALq-kJ5C6CA861GJW"
uri = "file://artifacts/clark-kent/public/surreal2.png"
type = "image"
title = "Surreal 2 — Figura cobalto azul, fondo naranja"

[[outputs]]
id = "59azAFF5_9zxMGilRwjlE"
uri = "file://artifacts/clark-kent/public/surreal3.png"
type = "image"
title = "Surreal 3 — Pintura teatral roja/naranja"
